name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-deploy
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure Pages
        uses: actions/configure-pages@v5
      # Only set up Node & caching if a lock file exists to avoid warnings
      - name: Setup Node (only if lock file present)
        if: ${{ hashFiles('package-lock.json') != '' || hashFiles('npm-shrinkwrap.json') != '' || hashFiles('yarn.lock') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
        
      - name: Install (skip if no package.json)
        if: ${{ hashFiles('package.json') != '' }}
        run: npm ci

      - name: Build (skip if no build script)
        if: ${{ hashFiles('package.json') != '' }}
        run: |
          if npm pkg get scripts.build | grep -qv 'undefined'; then npm run build; else echo "No build script defined"; fi

      - name: Prepare dist folder
        run: |
          set -euo pipefail
          echo "Working dir: $(pwd)"
          echo "Listing root files:"; ls -1 || true
          mkdir -p dist
          if [ ! -f dist/index.html ]; then
            echo "Preparing static files..."
            files_copied=0
            for f in index.html style.css main.js; do
              if [ -f "$f" ]; then
                echo "Copying $f"; cp "$f" dist/; files_copied=$((files_copied+1));
              else
                echo "(skip) $f not found";
              fi
            done
            if [ -d assets ]; then
              echo "Syncing assets/"; rsync -a assets/ dist/assets/ || cp -r assets dist/assets || true
            fi
            if [ $files_copied -eq 0 ] && [ ! -d assets ]; then
              echo "WARNING: No core static files found; creating placeholder index.html";
              echo '<!DOCTYPE html><meta charset="utf-8"><title>Empty Site</title><h1>Placeholder</h1>' > dist/index.html
            fi
          else
            echo "Existing build output detected (dist/index.html present)."
          fi
          echo "Dist contents:"; ls -al dist

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
